/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author ai
 */
public class Biner extends javax.swing.JDialog {
String s;
    /**
     * Creates new form Biner
     */
    public Biner(java.awt.Frame parent, boolean modal,String s) {
        super(parent, modal);
        this.s=s;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        tab.addTab("tab1", jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        new Thread(new Runnable() {
            @Override
            public void run() {
                muat();
            }
        }).start();
    }//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTabbedPane tab;
    // End of variables declaration//GEN-END:variables

    private void muat() {
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
    try {
        jalan();
    } catch (IOException ex) {
        Logger.getLogger(Biner.class.getName()).log(Level.SEVERE, null, ex);
    }
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }

    private void jalan() throws IOException {
        java.io.File f=new java.io.File(s);
        javax.swing.JScrollPane scrl=null;
        javax.swing.JTextArea t=null;
        int x=1,y=0;
        for(byte b:java.nio.file.Files.readAllBytes(f.toPath())){
            if(null==scrl&&t==null){
                initSek(scrl,t,x);
                x++;
                y++;
                t.setText(t.getText()+b+" ");
                continue;
            }if(y==4000){
                y=0;
                initSek(scrl,t,x);
                x++;
                t.setText(t.getText()+b+" ");
            }else t.setText(t.getText()+b+" ");
        }
    }

    private void initSek(JScrollPane scrl, JTextArea t, int x) {
        scrl=new javax.swing.JScrollPane();
        t=new javax.swing.JTextArea();
        scrl.setViewportView(t);
        t.setEditable(false);
        t.setLineWrap(true);
        t.setWrapStyleWord(true);
        tab.add(""+x, scrl);
    }
}